version: '3.8'

services:
  product-info-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Optional: Chrome-only test service zur Verifikation
  chrome-test:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["google-chrome", "--version"]
    profiles: ["test"]