# Docker Compose f체r lokale Azure-Tests
# Testet das Dockerfile.azure-fixed lokal vor Azure-Deployment
version: '3.8'

services:
  product-info-azure-test:
    build:
      context: .
      dockerfile: Dockerfile.azure-fixed
    container_name: product-info-azure-test
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      # Optional: OpenAI API Key f체r vollst채ndige Tests
      # - OPENAI_API_KEY=your_openai_api_key_here
    volumes:
      # Optional: Mount f체r Logs
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Chrome-Test Service - Testet nur die Chrome-Installation
  chrome-test:
    build:
      context: .
      dockerfile: Dockerfile.azure-fixed
    container_name: chrome-test
    command: ["google-chrome-stable", "--version"]
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable