# =================================================================
# FINALE, SYNTAKTISCH KORRIGIERTE WORKFLOW-DATEI
# =================================================================
name: Build and Deploy Container to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ------ JOB 1: BUILD ------
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.build-and-push.outputs.image }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/product-information-generator:${{ github.sha }}

  # ------ JOB 2: DEPLOY (Mit korrekter Syntax) ------
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      # Hinzugefügter Debug-Schritt zur Verifizierung
      - name: "DEBUG: Verify correct workflow is running"
        run: echo "SUCCESS: Der korrekte Deploy-Job mit Publish Profile wurde gestartet."
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Product-Information-Generator-Final'
          images: ${{ needs.build.outputs.image_name }} 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
