# Name des Workflows
name: Build and Deploy Container to Azure Web App

# Trigger: Startet bei Push auf den main-Branch oder manuell
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Definition der Jobs
jobs:
  # =================================================================
  # JOB 1: BUILD (Dieser Teil ist korrekt und bleibt unverändert)
  # Baut das Docker-Image und pusht es in Ihre private Registry
  # =================================================================
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/product-information-generator:${{ github.sha }}
    
    outputs:
      image: ${{ secrets.ACR_LOGIN_SERVER }}/product-information-generator:${{ github.sha }}

  # =================================================================
  # JOB 2: DEPLOY (Dieser Teil wurde angepasst)
  # Stellt das neue Image in der Azure Web App bereit
  # =================================================================
  deploy:
    runs-on: ubuntu-latest
    needs: build # Stellt sicher, dass dieser Job erst nach erfolgreichem 'build' startet
    
    steps:
      # DER "AZURE LOGIN"-SCHRITT WURDE HIER BEWUSST ENTFERNT.
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Product-Information-Generator-Final' # Name Ihrer Web App
          images: ${{ needs.build.outputs.image }} # Holt den Image-Namen aus dem vorherigen Job
          # DIESE NEUE ZEILE VERWENDET DAS PUBLISH PROFILE ZUR AUTHENTIFIZIERUNG
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
